GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/646f67c12910fc2bd94a9906

###

POST http://localhost:3000/subscribers/
Content-Type: application/json

{
      "name": "Člověk",
      "subscribedToChannel": "PewDiePie"
}

###
DELETE http://localhost:3000/subscribers/64746f84cbf84d1f8646523e

###

PATCH http://localhost:3000/subscribers/646f67c12910fc2bd94a9906
Content-Type: application/json

{
      "name": "Nove jmeno"
}